print(2+3)      # additional(+)
print(3-1)      # subtraction(-)
print(2*3)      # multiplication(*)
print(3/2)      # division(/)
print(3**2)     # exponential(**)
print(3 % 2)    # modulus(%)
print(3//2)     # Floor division operator(//)
